kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"eap7-app-release-server:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"eap7-app-release-server\")].image"}]
    openshift.io/generated-by: OpenShiftNewApp
  name: eap7-app-release-server
#  namespace: myproject
  labels:
    app: eap7-app-release-server
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: eap7-app-release-server
  template:
    metadata:
      labels:
        deployment: eap7-app-release-server
    spec:
      containers:
        - name: eap7-app-release-server
          image: >-
            image-registry.openshift-image-registry.svc:5000/myproject/eap7-app:latest
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          env:
            - name: POSTGRESQL_DATABASE
              value: sampledb
            - name: POSTGRESQL_DATASOURCE
              value: demo-ds
            - name: POSTGRESQL_PASSWORD
              value: admin
            - name: POSTGRESQL_SERVICE_HOST
              value: postgresql
            - name: POSTGRESQL_USER
              value: admin
---
kind: Service
apiVersion: v1
metadata:
  name: eap7-app-release-server
  namespace: myproject
  labels:
    app: eap7-app-release-server
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: eap7-app-release-server
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: eap7-app-release-server
  namespace: myproject
  labels:
    app: eap7-app-release-server
spec:
  to:
    kind: Service
    name: eap7-app-release-server
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
