apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-05-03T16:55:51Z"
  generation: 4
  name: eap-test-app
  resourceVersion: "274943"
  uid: 94d332e2-d690-4b35-9e1e-278dc4f3a97a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: eap-test-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eap-test-app
    spec:
      containers:
      - env:
        - name: POSTGRESQL_DATABASE
          value: sampledb
        - name: POSTGRESQL_USER
          value: admin
        - name: POSTGRESQL_PASSWORD
          value: admin
        - name: POSTGRESQL_SERVICE_DEMO
          value: postgresql-demo
        - name: POSTGRESQL_SERVICE_SECOND
          value: postgresql-second
        image: image-registry.openshift-image-registry.svc:5000/kkhan1-dev/eap7-app:latest
        imagePullPolicy: Always
        name: container
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30